### ISSUE TITLE
java.lang.IllegalArgumentException: already added

### ISSUE THREAD

**Issue by DenisSokoloff** [GrumpyCarrot/Android_Play_Games_Services_ANE#2]
I have this error 

```
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;
    at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
    at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
    at com.android.dx.command.dexer.Main.processClass(Main.java:737)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
    at com.android.dx.command.dexer.Main.access$300(Main.java:83)
    at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:637)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
    at com.android.dx.command.dexer.Main.run(Main.java:247)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting

```

Check my settings:

http://prntscr.com/b6drmz
http://prntscr.com/b6dsep
http://prntscr.com/b6dssx
http://prntscr.com/b6dtev

Myabe I have conflicts with other ANE?

**Comment by DFABRIK** [comment]
hi, any clue?

**Comment by agnither** [comment]
same problem here

**Comment by majidatidrai** [comment]
Same here too
